image: golang:1.16-alpine

variables:
  REPO_NAME: gitlab.roessner-net.de/croessner/geoip-policyd
  CGO_ENABLED: 0
  GOOS: linux
  GOARCH: amd64

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  #- test
  - build
  #- deploy

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/geoip-policyd
  artifacts:
    paths:
      - geoip-policyd
