version: "3.8"

services:

  geoip-policyd:
    image: geoip-policyd:latest
    logging:
      driver: journald
      options:
        tag: geoip-policyd
    network_mode: host
    environment:
      - TZ=Europe/Berlin
      - SERVER_ADDRESS=127.0.0.1
      - SERVER_PORT=4646
      - HTTP_ADDRESS=127.0.0.1:8080
      - REDIS_ADDRESS=127.0.0.1
      - REDIS_PORT=6379
      - REDIS_DATABASE_NUMBER=0
      - GEOIP_PATH=/GeoLite2-City.mmdb
      - CUSTOM_SETTINGS_PATH=/custom.json
    volumes:
      - /usr/share/GeoIP/GeoLite2-City.mmdb:/GeoLite2-City.mmdb:ro,Z
      - ./custom.json:/custom.json:ro,Z
