services:

  geoip-policyd:
    image: geoip-policyd:latest
    logging:
      driver: journald
      options:
        tag: geoip-policyd
    network_mode: host
    environment:
      - GEOIPPOLICYD_SERVER_ADDRESS=127.0.0.1
      - GEOIPPOLICYD_SERVER_PORT=4646
      - GEOIPPOLICYD_HTTP_ADDRESS=127.0.0.1
      - GEOIPPOLICYD_HTTP_PORT=8080
      - GEOIPPOLICYD_REDIS_ADDRESS=127.0.0.1
      - GEOIPPOLICYD_REDIS_PORT=6379
      - GEOIPPOLICYD_REDIS_DATABASE_NUMBER=0
      - GEOIPPOLICYD_GEOIP_PATH=/GeoLite2-City.mmdb
      - GEOIPPOLICYD_CUSTOM_SETTINGS_PATH=/custom.json
    volumes:
      - /usr/share/GeoIP/GeoLite2-City.mmdb:/GeoLite2-City.mmdb:ro,Z
      - ./custom.json:/custom.json:ro,Z
