---
# file: handlers/main.yml

- name: Restart geoip-policyd
  ansible.builtin.service:
    name: geoip-policyd
    state: restarted
  listen:
    - Restart and test

- name: Test geoip-policyd
  wait_for:
    host: "{{ destination_host }}"
    port: "{{ geoippolicyd['port'] }}"
    timeout: 2
  listen:
    - Restart and test

