style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/croessner/geoip-policyd
options:
  commits:
    filters:
      Type:
        - Add
        - Change
        - Feat
        - Fix
        - Remove
        - Perf
        - Refactor
        - Test
        - Docs
        - Build
        - Ci
        - Vendor
        - Security
        - Chore
  commit_groups:
    title_maps:
      Add: Features
      Change: Changes
      Feat: Features
      Fix: Bug Fixes
      Remove: Removed
      Perf: Performance Improvements
      Refactor: Code Refactoring
      Test: Tests
      Docs: Documentation
      Build: Build and Packaging
      Ci: Continuous Integration
      Vendor: Dependencies
      Security: Security
      Chore: Maintenance
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
