name: Release Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release Build on ${{ matrix.goos }} / ${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Build project
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -mod=vendor -ldflags="-s -X main.version=${GITHUB_REF#refs/heads/})-${GITHUB_SHA:0:8}" -o geoip-policyd-${{ matrix.goos }}-${{ matrix.goarch }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: geoip-policyd-${{ matrix.goos }}-${{ matrix.goarch }}-binary
          path: geoip-policyd-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.geoip-policyd_RELEASE }}
          files: geoip-policyd-${{ matrix.goos }}-${{ matrix.goarch }}
