name: Run Unit Tests

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - features

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Enable Go Modules
        run: go env -w GO111MODULE=on

      - name: Use Vendored Dependencies
        run: go env -w GOFLAGS=-mod=vendor

      - name: Run Unit Tests
        run: go test $(go list ./... | grep -v /vendor/)
